name: flutter_native_app_state
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: asia.ivity.flutter_native_app_state
        pluginClass: FlutterNativeAppStatePlugin
      ios:
        pluginClass: FlutterNativeAppStatePlugin